#' @title Mapping of FastCAT data
#'
#' @description Once make_dataframe_fc() has been run, then map_fc can be
#' used. This function makes a station map from the dataframe generated.
#' The rendered map will be located in the plot folder within the current
#' folder.
#' @param current_path The path to the directory where the .csv file
#' generated by make_dataframe_fc is located.
#' @param map_type Determines the type of map which will be returned. The
#' default map is a station map. Map types are Station: returns map of
#' station locations, Sample intensity: returns a map of sampling intesity
#' for each "distance measure to be determined" hexagon, Salinity: returns an
#' map using a least-squares gridding method for the average of the depth_range
#' specified. If depth_range remains as NA, then the entire water column will
#' be averaged.Temperature: returns a map using a least-squares gridding method
#' for the average of the depth_range specified. If depth_range remains as NA,
#' then the entire water column will be averaged. Map types are as follows and
#' should be quoted: "Station", "Sample Intensity", "Salinity", and
#' "Temperature".
#' @param depth_range The desired depth range for either the "Salinity" or
#' "Temperature". If the parameter is left as NA, then the entire water
#' column will be averages.
#' @return A station map



map_fc <- function(current_path, map_type = "Station", depth_range = NA){

# find and read in the file created by make_dataframe_fc()---------------------

fc_data <- readr::read_csv(list.files(path = current_path,
                                      pattern = "\\EcoDAAT.csv$",
                                      ignore.case = TRUE,
                                      include.dirs = TRUE,
                                      full.names = TRUE),
                    col_types = cols(CRUISE = col_character(),
                                     STATION_NAME = col_integer(),
                                     HAUL_NAME = col_integer(),
                                     FOCI_GRID = col_character(),
                                     DATE = col_date(),
                                     LAT = col_double(),
                                     LON = col_double(),
                                     DEPTH_BOTTOM = col_integer(),
                                     DEPTH = col_integer(),
                                     TEMPERATURE1 = col_double(),
                                     SALINITY1 = col_double()))%>%
            dplyr::select(CRUISE, STATION_NAME, HAUL_NAME, FOCI_GRID,
                          DATE, LAT, LON, DEPTH_BOTTOM, DEPTH,
                          TEMPERATURE1, SALINITY1)

# bring in the shape files to make the basemap --------------------------------

MAP <- sf::st_read(dsn = "inst/extdata",layer = "Alaska_dcw_polygon_Project",
                   quiet = TRUE)

# tranform into WGS84 coordinate system----------------------------------------

MAP <- sf::st_transform(MAP, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# bring in 200m bathymetry contour --------------------------------------------

BATH_200 <- sf::st_read(dsn = "inst/extdata", layer = "ne_10m_bathymetry_K_200",
                        quiet = TRUE)

# transform into WGS84 coordinate system---------------------------------------

BATH_200 <- sf::st_transform(BATH_200,
                         "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# coordinate bounding box for map----------------------------------------------

fc_xlim <- c(min(fc_data$LON, na.rm = TRUE) - 2,
             max(fc_data$LON, na.rm = TRUE) + 2)
fc_ylim <- c(min(fc_data$LAT, na.rm = TRUE) - 2,
             max(fc_data$LAT, na.rm = TRUE) + 2)

# Map title--------------------------------------------------------------------
map_dir_name <- paste(current_path, paste(unique(fc_data$CRUISE),
                                          "_Station_map",".png",sep = ""),
                      sep = "/")

map_title <- paste("Cruise",unique(fc_data$CRUISE), sep = " ")

# Station map data if Station.haul---------------------------------------------

Station_map <- fc_data %>%
  dplyr::select(CRUISE, STATION_NAME, HAUL_NAME, LAT, LON)%>%
  tidyr::unite(STATION_HAUL, STATION_NAME, HAUL_NAME, sep = ".")%>%
  dplyr::distinct(STATION_HAUL, .keep_all = TRUE)


# map--------------------------------------------------------------------------

fc_map <- ggplot2::ggplot()+
  ggplot2::geom_sf(color = "black", data = BATH_200[3], alpha = 0)+
  ggplot2::geom_sf(fill ="#a7ad94", color = "black", data = MAP[1])+
  ggspatial::annotation_scale(location = "bl", width_hint = 0.5,
                              unit_category = "metric")+
  ggplot2::coord_sf(xlim = fc_xlim, ylim = fc_ylim)+
  ggplot2::geom_point(aes(LON, LAT), size = 4, shape = 21, color = "black",
                      fill = "gray", data = Station_map)+
  ggrepel::geom_text_repel(aes(LON, LAT, label = STATION_HAUL), size = 5,
                     color = "black",data = Station_map)+
  ggplot2::theme_bw()+
  ggplot2::xlab(label = "Longitude")+
  ggplot2::ylab(label = "Latitude")+
  ggplot2::ggtitle(label = map_title)+
  ggplot2::theme(
    axis.text.y = element_text(face = "bold", size = 12),
    axis.text.x = element_text(face = "bold", size = 12),
    axis.title = element_text(face = "bold", size = 12),
    title = element_text(face = "bold", size = 14))

# write map to file-------------------------------------------------------
png(filename = map_dir_name, width = 600, height = 600, units = "px",
    bg = "transparent")

print(fc_map)

dev.off()

}




