#' @title Mapping of FastCAT data
#'
#' @description Once make_dataframe_fc() has been run, then map_fc can be
#' used. This function makes a station map from the dataframe generated.
#' The rendered map will be located in the plot folder within the current
#' folder.
#' @param current_path The path to the directory where the .csv file
#' generated by make_dataframe_fc is located.
#' @param map_type Determines the type of map which will be returned. The
#' default map is a station map. Map types are Station: returns map of
#' station locations, Sample intensity: returns a map of sampling intesity
#' for each 0.3 decimal degrees which is around 30km for the regions that are
#' sampled hexagon, Salinity: returns an
#' map using a least-squares gridding method for the average of the depth_range
#' specified. If depth_range remains as NA, then the entire water column will
#' be averaged.Temperature: returns a map using a least-squares gridding method
#' for the average of the depth_range specified. If depth_range remains as NA,
#' then the entire water column will be averaged. Map types are as follows and
#' should be quoted: "Station", "Sample Intensity", "Salinity", and
#' "Temperature".
#' @param depth_range The desired depth range for either the "Salinity" or
#' "Temperature". If the parameter is left as NA, then the entire water
#' column will be averaged.Takes a two value vector, a minimum and maximum of
#' desired depth range. For example a depth range of 5-10 meters would be
#' entered as such c(5,10).
#' @return A map of the desired type and depth range for a single cruise.



map_fc <- function(current_path, map_type = "Station", depth_range = NA){

# find and read in the file created by make_dataframe_fc()---------------------

fc_data <- readr::read_csv(list.files(path = current_path,
                                      pattern = "\\EcoDAAT.csv$",
                                      ignore.case = TRUE,
                                      include.dirs = TRUE,
                                      full.names = TRUE),
                    col_types = cols_only(CRUISE = col_character(),
                                     STATION_NAME = col_integer(),
                                     HAUL_NAME = col_integer(),
                                     FOCI_GRID = col_character(),
                                     DATE = col_date(),
                                     LAT = col_double(),
                                     LON = col_double(),
                                     DEPTH_BOTTOM = col_integer(),
                                     DEPTH = col_integer(),
                                     TEMPERATURE1 = col_double(),
                                     SALINITY1 = col_double()))

# bring in the shape files to make the basemap --------------------------------

MAP <- sf::st_read(dsn = "inst/extdata",layer = "Alaska_dcw_polygon_Project",
                   quiet = TRUE)

# tranform into WGS84 coordinate system----------------------------------------

MAP <- sf::st_transform(MAP, "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# bring in 200m bathymetry contour --------------------------------------------

BATH_200 <- sf::st_read(dsn = "inst/extdata", layer = "ne_10m_bathymetry_K_200",
                        quiet = TRUE)

# transform into WGS84 coordinate system---------------------------------------

BATH_200 <- sf::st_transform(BATH_200,
                         "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# coordinate bounding box for map----------------------------------------------

fc_xlim <- c(min(fc_data$LON, na.rm = TRUE) - 2,
             max(fc_data$LON, na.rm = TRUE) + 2)
fc_ylim <- c(min(fc_data$LAT, na.rm = TRUE) - 2,
             max(fc_data$LAT, na.rm = TRUE) + 2)

# Map title--------------------------------------------------------------------

map_dir_name <- if(map_type == "Station" | map_type == "Sample Intensity"){

  paste(current_path, paste(unique(fc_data$CRUISE),
                            "_", map_type,".png",sep = ""), sep = "/")

} else if(map_type == "Salinity" & is.na(depth_range[1]) |
          map_type == "Temperature" & is.na(depth_range[1])){

  paste(current_path, paste(unique(fc_data$CRUISE),
                            "_", map_type,"_total water column",
                            ".png",sep = ""), sep = "/")

} else if(map_type == "Salinity" & !is.na(depth_range[1]) |
          map_type == "Temperature" !is.na(depth_range[1])){

  paste(current_path, paste(unique(fc_data$CRUISE),
                            "_", map_type,"_",
                            min(depth_range, na.rm = TRUE), "_",
                            max(depth_range, na.rm = TRUE),
                            ".png",sep = ""), sep = "/")
}


map_title <- if(map_type == "Station" | map_type == "Sample Intensity"){

    paste("Cruise ",unique(fc_data$CRUISE), ": ",map_type, sep = "")

    } else if(map_type == "Salinity" & is.na(depth_range[1]) |
              map_type == "Temperature" & is.na(depth_range[1])){

    paste("Cruise ",unique(fc_data$CRUISE), ": ",map_type,
         ", total water column",sep = "")

    } else if(map_type == "Salinity" & !is.na(depth_range[1]) |
              map_type == "Temperature" & !is.na(depth_range[1])){

    paste("Cruise ",unique(fc_data$CRUISE), ": ",map_type," ",
        min(depth_range, na.rm = TRUE), " to ",
        max(depth_range, na.rm = TRUE), " m depth", sep = "")
  }

# Dataframes and calculations for each map_type -------------------------------

map_data <- if(map_type == "Station" | map_type == "Sample Intensity"){

  fc_data %>%
    dplyr::select(CRUISE, STATION_NAME, HAUL_NAME, LAT, LON)%>%
    tidyr::unite(STATION_HAUL, STATION_NAME, HAUL_NAME, sep = ".")%>%
    dplyr::distinct(STATION_HAUL, .keep_all = TRUE)

} else if(map_type == "Salinity"){

  MAP_IDW <- fc_data %>%
    dplyr::filter(if(is.na(depth_range[1])){
      DEPTH >= min(DEPTH, na.rm = TRUE) &
        DEPTH <= max(DEPTH, na.rm = TRUE)
      }else{
      DEPTH >= min(depth_range, na.rm = TRUE) &
        DEPTH <= max(depth_range, na.rm = TRUE)})%>%
    dplyr::group_by(LAT,LON)%>%
    dplyr::summarise(SALINITY1 = mean(SALINITY1, na.rm = TRUE))%>%
    dplyr::select(LON, LAT, SALINITY1)%>%
    dplyr::mutate_all(na.omit)


  WGS84 <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")

  MAP_IDW_SPAT <- sp::SpatialPointsDataFrame(coords = MAP_IDW[,c("LON","LAT")],
                                         data = MAP_IDW,
                                         proj4string = WGS84)

  x.range <- as.integer(c(min(MAP_IDW$LON, na.rm = TRUE)-1,
                          max(MAP_IDW$LON, na.rm = TRUE)+1))

  y.range <- as.integer(c(min(MAP_IDW$LAT, na.rm = TRUE)-1,
                          max(MAP_IDW$LAT, na.rm = TRUE)+1))

  grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.25),
                     y = seq(from = y.range[1], to = y.range[2], by = 0.25))

  sp::coordinates(grd) <- ~ x + y

  sp::gridded(grd) <- TRUE

  sp::proj4string(grd) <- WGS84


  idw <- gstat::idw(formula = MAP_IDW$SALINITY1 ~ 1, locations = MAP_IDW_SPAT,
             newdata = grd, idp = 3)

  idw.output <- as.data.frame(idw)
  names(idw.output)[1:3] <- c("LON","LAT","SALINITY1")

  #Make the hull and the buffer

  IDW_raster <- raster::rasterFromXYZ(idw.output[,1:3],crs = WGS84)
  IDW_hull <- rgeos::gConvexHull(MAP_IDW_SPAT)
  IDW_buff <- withCallingHandlers(suppressWarnings(
    rgeos::gBuffer(IDW_hull,width = .5)))
  IDW_buff_WGS84 <- sp::spTransform(IDW_buff, WGS84)

  IDW_raster_crop <- raster::mask(IDW_raster, IDW_buff_WGS84)
  #try this
  Raster_crop_pt <- raster::rasterToPoints(IDW_raster_crop, spatial = TRUE)

  Out_crop <- cbind(Raster_crop_pt@coords, Raster_crop_pt@data)

  names(Out_crop) <- c("LON","LAT","SALINITY1")

  Out_crop

} else if(map_type == "Temperature"){


  MAP_IDW <- fc_data %>%
    dplyr::filter(if(is.na(depth_range[1])){
      DEPTH >= min(DEPTH, na.rm = TRUE) &
        DEPTH <= max(DEPTH, na.rm = TRUE)
    }else{
      DEPTH >= min(depth_range, na.rm = TRUE) &
        DEPTH <= max(depth_range, na.rm = TRUE)})%>%
    dplyr::group_by(LAT,LON)%>%
    dplyr::summarise(TEMPERATURE1 = mean(TEMPERATURE1, na.rm = TRUE))%>%
    dplyr::select(LON, LAT, TEMPERATURE1)%>%
    dplyr::mutate_all(na.omit)


  WGS84 <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")

  MAP_IDW_SPAT <- sp::SpatialPointsDataFrame(coords = MAP_IDW[,c("LON","LAT")],
                                             data = MAP_IDW,
                                             proj4string = WGS84)

  x.range <- as.integer(c(min(MAP_IDW$LON, na.rm = TRUE)-1,
                          max(MAP_IDW$LON, na.rm = TRUE)+1))

  y.range <- as.integer(c(min(MAP_IDW$LAT, na.rm = TRUE)-1,
                          max(MAP_IDW$LAT, na.rm = TRUE)+1))

  grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.25),
                     y = seq(from = y.range[1], to = y.range[2], by = 0.25))

  sp::coordinates(grd) <- ~ x + y

  sp::gridded(grd) <- TRUE

  sp::proj4string(grd) <- WGS84


  idw <- gstat::idw(formula = MAP_IDW$TEMPERATURE1 ~ 1, locations = MAP_IDW_SPAT,
                    newdata = grd, idp = 3)

  idw.output <- as.data.frame(idw)
  names(idw.output)[1:3] <- c("LON","LAT","TEMPERATURE1")

  #Make the hull and the buffer

  IDW_raster <- raster::rasterFromXYZ(idw.output[,1:3],crs = WGS84)
  IDW_hull <- rgeos::gConvexHull(MAP_IDW_SPAT)
  IDW_buff <- rgeos::withCallingHandlers(suppressWarnings(
    gBuffer(IDW_hull,width = .5)))
  IDW_buff_WGS84 <- sp::spTransform(IDW_buff, WGS84)

  IDW_raster_crop <- raster::mask(IDW_raster, IDW_buff_WGS84)
  #try this
  Raster_crop_pt <- raster::rasterToPoints(IDW_raster_crop, spatial = TRUE)

  Out_crop <- cbind(Raster_crop_pt@coords, Raster_crop_pt@data)

  names(Out_crop) <- c("LON","LAT","TEMPERATURE1")

  Out_crop


} else{
  warning("No such map_type name, check spelling.")
}


# Plot object by map_type to add to map ---------------------------------------

map_choice <- if(map_type == "Station"){

  ggplot2::ggplot()+
    ggplot2::geom_point(aes(LON, LAT), size = 2, shape = 21,
                                      color = "black", fill = "#7394b5",
                                      data = map_data)#+
    #ggrepel::geom_text_repel(aes(LON, LAT, label = STATION_HAUL),
                             #size = 5, color = "black",
                             #data = station_map)

} else if(map_type == "Sample Intensity"){

  intensity_color <- c("#013565", "#1C3983", "#3C3E87",
                       "#524685", "#664D83", "#785383", "#8C5A82", "#A05F7F",
                       "#B66478", "#CC686D", "#E0705D", "#EF7B4C", "#F78C41",
                       "#FAA13D", "#F9B642", "#F5CD4D", "#EFE35B", "#E5FA6A")


  if(length(unique(station_map$CRUISE)) <= 2){

  ggplot2::ggplot()+
    ggplot2::geom_hex(aes(LON, LAT), binwidth = 0.5, alpha = 0.9,
                      data = station_map)+
    ggplot2::scale_fill_gradientn(colors = intensity_color,
                                  breaks = seq(1,10, by = 2),
                                  labels = seq(1,10, by = 2),
                                  limits = c(1,10),
                                  name = "Casts(n)")+
    ggplot2::scale_color_gradientn(colors = intensity_color,
                                   breaks = seq(1,10, by = 2),
                                   labels = seq(1,10, by = 2),
                                   limits = c(1,10))
  }else{

    ggplot2::ggplot()+
      ggplot2::geom_hex(aes(LON, LAT), binwidth = 1, alpha = 0.9,
                        data = station_map)+
      ggplot2::scale_fill_gradientn(colors = intensity_color,
                                    breaks = seq(1,40, by = 5),
                                    labels = seq(1,40, by = 5),
                                    limits = c(1,40),
                                    name = "Casts(n)")+
      ggplot2::scale_color_gradientn(colors = intensity_color,
                                     breaks = seq(1,40, by = 5),
                                     labels = seq(1,40, by = 5),
                                     limits = c(1,40))


  }
} else if(map_type == "Salinity"){

# The limits for salinity were set based on values from historical fastcat
# data. The low end is set at 27 psu and 1 + the high end 35. The mode for the
# salinity data was 33. Contour for salinity is set to .5 PSU.
  salinity_color <- c("#2B1470", "#2C1D8A", "#212F96", "#114293", "#08518F",
                      "#0E5E8B", "#1A6989", "#267488", "#318088", "#3A8B88",
                      "#439787", "#4BA385", "#56AF81", "#64BA7B", "#77C574",
                      "#91CF6C", "#B0D66C", "#CCDE78", "#E6E58A", "#FEEEA0")

  ggplot2::ggplot()+
    ggplot2::geom_tile(aes(x = LON, y = LAT, fill = SALINITY1), size = 1,
            data = map_data)+
    ggplot2::geom_contour(aes(x = LON, y = LAT, z = SALINITY1),
                          binwidth = 0.5,data = map_data,
                 color = "#f0ead6", size = .5)+
    ggplot2::scale_fill_gradientn(colors = salinity_color,
                                  breaks = seq(27,35, by = 2),
                                  labels = seq(27,35, by = 2),
                                  limits = c(27,35),
                                  name = expression(bold("PSU")))+
    ggplot2::scale_color_gradientn(colors = salinity_color,
                                   breaks = seq(27,35, by = 2),
                                   labels = seq(27,35, by = 2),
                                   limits = c(27,35))

} else if(map_type == "Temperature"){

# The limits for temperature were set on the low end the temperature at which
# seaeater freezes -2C and the high end of 18C which is 2 degrees higher than
# the highest recored temperature from all fastcat data. This will give wiggle
# room for higher temperatures in the future. The mode for temperature is 6C.
# Binwidth for the temperature contour is 1 degree C.

  temperature_color <- c("#0E0C71", "#1D159E", "#1D26C9", "#174CBB", "#2F63B3",
                         "#4977B2", "#658AB4", "#7F9DB9", "#9AAFC1", "#B6C3CD",
                         #"#D2D7DB" "#EEEDED" "#E0D2CF"
                         "#D6B8B1", "#CB9F93", "#C28676", "#B86E5A", "#AD543E",
                         "#A23925", "#931A11", "#7B0413", "#5D0311", "#41000B")

  ggplot2::ggplot()+
    ggplot2::geom_tile(aes(x = LON, y = LAT, fill = TEMPERATURE1), size = 1,
                       data = map_data)+
    ggplot2::geom_contour(aes(x = LON, y = LAT, z = TEMPERATURE1),
                          binwidth = 1, data = map_data,
                          color = "#4c7f7f", size = .25)+
    ggplot2::scale_fill_gradientn(colors = temperature_color,
                                  breaks = seq(-2,18, by = 4),
                                  labels = seq(-2,18, by = 4),
                                  limits = c(-2,18),
                                  name = expression(bold( ~degree~C )))+
    ggplot2::scale_color_gradientn(colors = temperature_color,
                                   breaks = seq(-2,18, by = 4),
                                   labels = seq(-2,18, by = 4),
                                   limits = c(-2,18))
} else{
  warning("No such map_type name, check spelling.")
}

# map--------------------------------------------------------------------------

fc_map <- map_choice +
              ggplot2::geom_sf(color = "black", data = BATH_200[3], alpha = 0)+
              ggplot2::geom_sf(fill ="#a7ad94", color = "black", data = MAP[1])+
              ggspatial::annotation_scale(location = "bl", width_hint = 0.5,
                              unit_category = "metric")+
              ggplot2::coord_sf(xlim = fc_xlim, ylim = fc_ylim)+
              ggplot2::theme_bw()+
              ggplot2::xlab(label = "Longitude")+
              ggplot2::ylab(label = "Latitude")+
              ggplot2::ggtitle(label = map_title)+
              ggplot2::theme(
                axis.text.y = element_text(face = "bold", size = 12),
                axis.text.x = element_text(face = "bold", size = 12),
                axis.title = element_text(face = "bold", size = 12),
                title = element_text(face = "bold", size = 14))

# write map to file-------------------------------------------------------
png(filename = map_dir_name, width = 600, height = 600, units = "px",
    bg = "transparent")

print(fc_map)

dev.off()

 }




